# Generated by Django 5.2.15 on 2026-06-19 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
