#!/usr/bin/env python3
"""Check that the RAVID repository covers the assessment's required surface area.

Run from the repository root:

    python .agents/scripts/check_assessment_coverage.py            # lenient (foundation)
    python .agents/scripts/check_assessment_coverage.py --strict   # hard-fail on gaps

Unlike `validate_agents.py` (which gates the foundation inventory that exists on
every branch), the coverage markers below describe PRODUCT behavior that lands
in later feature slices. On the foundation branch those markers are legitimately
absent, so by default a missing required marker group is a WARNING and the
script exits 0. Pass `--strict` (e.g. on the final delivery branch / in CI on
`main`) to turn missing required groups into a hard failure (exit 1).

Pure stdlib. Tolerant of files that do not exist yet.
"""
from __future__ import annotations

import sys
from pathlib import Path

# scripts/ -> .agents/ -> <repo root>
ROOT = Path(__file__).resolve().parents[2]

# This directory holds the validation scripts. They embed every coverage marker
# string as data (the MARKERS table below), so scanning them would make every
# marker spuriously "present". Exclude the scripts dir from the corpus.
SCRIPTS_DIR = Path(__file__).resolve().parent

# Directories we never want to scan (vendored deps, VCS, caches, build output).
SKIP_DIR_NAMES = {
    ".git",
    ".venv",
    "venv",
    "env",
    "node_modules",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "migrations",  # autogenerated; not meaningful coverage signal
    "staticfiles",
    "static",
    "dist",
    "build",
    ".idea",
    ".vscode",
}

# Only scan text-ish files; skip binaries and large blobs.
TEXT_SUFFIXES = {
    ".py",
    ".md",
    ".txt",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".json",
    ".env",
    ".example",
    ".sh",
    ".dockerfile",
    ".conf",
    "",  # extensionless (Dockerfile, Makefile, .env.example handled below)
}

# Extensionless filenames worth scanning even though they have no suffix.
TEXT_FILENAMES = {
    "Dockerfile",
    "Makefile",
    ".env",
    ".env.example",
    ".gitignore",
    "docker-compose.yml",
    "docker-compose.yaml",
}

MAX_BYTES = 2_000_000  # skip files larger than ~2 MB


# --- Coverage marker groups -------------------------------------------------
# Each group maps a human label to a list of alternative substrings (already
# lowercase); a group is "present" if ANY of its alternatives appears anywhere
# in the scanned corpus. `required=True` groups participate in the pass/fail
# decision; `required=False` groups are informational only.
#
# Markers are derived from the RAVID assessment surface area: documents upload +
# ingestion (LangChain load -> chunk -> embed -> Chroma), RAG chat/query via
# OpenRouter, task status, auth (JWT), async (Celery/Redis), observability
# (Loki/Grafana/Alloy), Docker delivery, and docs (README + OpenAPI/API docs).
class Marker:
    __slots__ = ("label", "terms", "required")

    def __init__(self, label: str, terms: list[str], required: bool = True) -> None:
        self.label = label
        self.terms = terms
        self.required = required


MARKERS = [
    Marker("upload-document endpoint", ["upload-document", "documents/upload"]),
    Marker("ingestion", ["ingest"]),
    Marker("embedding", ["embedding", "embed", "minilm", "huggingface"]),
    Marker("chunking", ["chunk", "recursivecharactertextsplitter", "textsplitter"]),
    Marker("chroma vector store", ["chroma"]),
    Marker("langchain", ["langchain"]),
    Marker("openrouter llm gateway", ["openrouter"]),
    Marker("retrieval", ["retriev"]),
    Marker("chat/query endpoint", ["chat/query", "chat-query"]),
    Marker("task status endpoint", ["documents/status", "task-status", "task_status"]),
    Marker("jwt auth", ["jwt", "simplejwt", "simple-jwt"]),
    Marker("celery", ["celery"]),
    Marker("redis", ["redis"]),
    Marker("loki", ["loki"]),
    Marker("grafana", ["grafana"]),
    Marker("alloy", ["alloy"]),
    Marker("docker compose", ["docker compose", "docker-compose"]),
    Marker("readme", ["readme"]),
    Marker("api docs / openapi", ["openapi", "api_contract", "swagger", "bruno", "postman"]),
]


def iter_text_files() -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        # Skip the scripts directory (it embeds every marker as data).
        if SCRIPTS_DIR in path.parents:
            continue
        # Skip anything under an excluded directory.
        if any(part in SKIP_DIR_NAMES for part in path.relative_to(ROOT).parts[:-1]):
            continue
        name = path.name
        suffix = path.suffix.lower()
        if name not in TEXT_FILENAMES and suffix not in TEXT_SUFFIXES:
            continue
        try:
            if path.stat().st_size > MAX_BYTES:
                continue
        except OSError:
            continue
        files.append(path)
    return files


def build_corpus() -> str:
    parts: list[str] = []
    for path in iter_text_files():
        try:
            parts.append(path.read_text(encoding="utf-8", errors="ignore").lower())
        except (OSError, UnicodeError):
            continue
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    strict = "--strict" in argv[1:]

    corpus = build_corpus()
    if not corpus:
        msg = "No scannable text files found under the repository root."
        if strict:
            print(f"ERROR: {msg}")
            return 1
        print(f"WARNING: {msg} (lenient mode; pass --strict to fail)")
        return 0

    present_required: list[str] = []
    missing_required: list[str] = []
    present_optional: list[str] = []
    missing_optional: list[str] = []

    for marker in MARKERS:
        found = any(term in corpus for term in marker.terms)
        if marker.required:
            (present_required if found else missing_required).append(marker.label)
        else:
            (present_optional if found else missing_optional).append(marker.label)

    print("RAVID assessment coverage report")
    print(f"  mode: {'strict' if strict else 'lenient (foundation-safe)'}")
    print(
        f"  required markers present: {len(present_required)}/"
        f"{len(present_required) + len(missing_required)}"
    )

    if present_required:
        print("Present:")
        for label in present_required:
            print(f"  + {label}")

    if missing_required:
        print("Absent:")
        for label in missing_required:
            print(f"  - {label}")

    if missing_optional:
        print("Absent (optional):")
        for label in missing_optional:
            print(f"  ~ {label}")

    if not missing_required:
        print("All required assessment coverage markers are present.")
        return 0

    if strict:
        print(
            "\nERROR (--strict): required coverage markers are missing. "
            "These must be present before final delivery."
        )
        return 1

    print(
        "\nWARNING: required coverage markers are missing, but this is allowed "
        "on the foundation branch (product code lands in later slices). "
        "Re-run with --strict on the delivery branch / in CI to enforce."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
